baseURL = 'https://trans.nrw/'
title = 'identiT⚧️'
enableEmoji = true
disableKinds = ['taxonomy', 'section']
theme = 'transnrw'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true
[languages]
    [languages.de-DE]
        languageCode = 'de-DE'
        contentDir = 'content/de-DE'
        languageName = 'Deutsch'
        weight = 1
    [languages.en-US]
        languageCode = 'en-US'
        contentDir = 'content/en-US'
        languageName = 'English'
        weight = 2

[params]
  [params.identiT]
      [params.identiT.Teamspeak]
          URL = 'ts3server://ts.trans.nrw'
      [params.identiT.Forum]
          URL = 'https://forum.trans.nrw'
          meetups = 'https://forum.trans.nrw/forumdisplay.php?fid=13'
      [params.identiT.Map]
          URL = 'https://map.trans.nrw'
      [params.identiT.redaktion]
          name = 'Thorger Jansen'
      [params.identiT.privacy]
          mail = 'admin@trans.nrw'
          name = 'Thorger Jansen'
          street = 'Im Westenfeld 28'
          city = '44801 Bochum'
          phone = '(DE) 15757214751'
      [params.identiT.impressum]
          mail = 'admin@trans.nrw'
          name = 'Thorger Jansen'
          street = 'Im Westenfeld 28'
          city = '44801 Bochum'
          phone = '(DE) 15757214751'
