name: Deploy to Remote Host

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Fix Tailwind CSS permissions
      run: chmod +x node_modules/.bin/tailwindcss
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
        
    - name: Build with Hugo
      run: hugo build --environment production

    - name: Deploy to VServer via SSH
      uses: burnett01/rsync-deployments@7.1.0
      with:
        switches: -avz --delete --rsync-path="rsync" --exclude='.git' --exclude='.github'
        path: "./public/"
        remote_path: "/var/www/trans.nrw/html/"
        remote_host: ${{ secrets.SERVER_IP }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: 2222
